package com.health.model;
// Generated 2017-2-15 15:54:26 by Hibernate Tools 5.0.2.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * ThAdminRoleOrganization generated by hbm2java
 */
@Entity
@Table(name = "th_admin_role_organization", catalog = "health")
public class ThAdminRoleOrganization implements java.io.Serializable {

	private Integer id;
	private String userId;
	private Integer roleId;
	private Integer organizationId;

	public ThAdminRoleOrganization() {
	}

	public ThAdminRoleOrganization(String userId, Integer roleId, Integer organizationId) {
		this.userId = userId;
		this.roleId = roleId;
		this.organizationId = organizationId;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "userId", length = 49)
	public String getUserId() {
		return this.userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	@Column(name = "roleId")
	public Integer getRoleId() {
		return this.roleId;
	}

	public void setRoleId(Integer roleId) {
		this.roleId = roleId;
	}

	@Column(name = "organizationId")
	public Integer getOrganizationId() {
		return this.organizationId;
	}

	public void setOrganizationId(Integer organizationId) {
		this.organizationId = organizationId;
	}

}
