package com.health.model;
// Generated 2017-4-6 17:32:02 by Hibernate Tools 5.1.0.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * ThCommonDiagnosis generated by hbm2java
 */
@Entity
@Table(name = "th_common_diagnosis", catalog = "health")
public class ThCommonDiagnosis implements java.io.Serializable {

	private Long id;
	private String parameter0;
	private String ehrId;
	private String parameter1;
	private String diagCode;
	private String diagName;
	private String parameter2;
	private String parameter3;
	private String diagDate;
	private String parameter4;
	private String parameter5;
	private String parameter6;
	private String parameter7;
	private String diagnosisTime;
	private String diagnosisTime2;
	private String parameter8;
	private String parameter9;
	private String parameter10;

	public ThCommonDiagnosis() {
	}

	public ThCommonDiagnosis(String parameter0, String ehrId, String parameter1, String diagCode, String diagName,
			String parameter2, String parameter3, String diagDate, String parameter4, String parameter5,
			String parameter6, String parameter7, String diagnosisTime, String diagnosisTime2, String parameter8,
			String parameter9, String parameter10) {
		this.parameter0 = parameter0;
		this.ehrId = ehrId;
		this.parameter1 = parameter1;
		this.diagCode = diagCode;
		this.diagName = diagName;
		this.parameter2 = parameter2;
		this.parameter3 = parameter3;
		this.diagDate = diagDate;
		this.parameter4 = parameter4;
		this.parameter5 = parameter5;
		this.parameter6 = parameter6;
		this.parameter7 = parameter7;
		this.diagnosisTime = diagnosisTime;
		this.diagnosisTime2 = diagnosisTime2;
		this.parameter8 = parameter8;
		this.parameter9 = parameter9;
		this.parameter10 = parameter10;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ID", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "parameter0", length = 100)
	public String getParameter0() {
		return this.parameter0;
	}

	public void setParameter0(String parameter0) {
		this.parameter0 = parameter0;
	}

	@Column(name = "EHR_ID", length = 100)
	public String getEhrId() {
		return this.ehrId;
	}

	public void setEhrId(String ehrId) {
		this.ehrId = ehrId;
	}

	@Column(name = "parameter1", length = 20)
	public String getParameter1() {
		return this.parameter1;
	}

	public void setParameter1(String parameter1) {
		this.parameter1 = parameter1;
	}

	@Column(name = "DIAG_CODE", length = 100)
	public String getDiagCode() {
		return this.diagCode;
	}

	public void setDiagCode(String diagCode) {
		this.diagCode = diagCode;
	}

	@Column(name = "DIAG_NAME", length = 200)
	public String getDiagName() {
		return this.diagName;
	}

	public void setDiagName(String diagName) {
		this.diagName = diagName;
	}

	@Column(name = "parameter2", length = 50)
	public String getParameter2() {
		return this.parameter2;
	}

	public void setParameter2(String parameter2) {
		this.parameter2 = parameter2;
	}

	@Column(name = "parameter3", length = 50)
	public String getParameter3() {
		return this.parameter3;
	}

	public void setParameter3(String parameter3) {
		this.parameter3 = parameter3;
	}

	@Column(name = "DIAG_DATE", length = 50)
	public String getDiagDate() {
		return this.diagDate;
	}

	public void setDiagDate(String diagDate) {
		this.diagDate = diagDate;
	}

	@Column(name = "parameter4", length = 50)
	public String getParameter4() {
		return this.parameter4;
	}

	public void setParameter4(String parameter4) {
		this.parameter4 = parameter4;
	}

	@Column(name = "parameter5", length = 50)
	public String getParameter5() {
		return this.parameter5;
	}

	public void setParameter5(String parameter5) {
		this.parameter5 = parameter5;
	}

	@Column(name = "parameter6", length = 50)
	public String getParameter6() {
		return this.parameter6;
	}

	public void setParameter6(String parameter6) {
		this.parameter6 = parameter6;
	}

	@Column(name = "parameter7", length = 50)
	public String getParameter7() {
		return this.parameter7;
	}

	public void setParameter7(String parameter7) {
		this.parameter7 = parameter7;
	}

	@Column(name = "diagnosisTime", length = 50)
	public String getDiagnosisTime() {
		return this.diagnosisTime;
	}

	public void setDiagnosisTime(String diagnosisTime) {
		this.diagnosisTime = diagnosisTime;
	}

	@Column(name = "diagnosisTime2", length = 45)
	public String getDiagnosisTime2() {
		return this.diagnosisTime2;
	}

	public void setDiagnosisTime2(String diagnosisTime2) {
		this.diagnosisTime2 = diagnosisTime2;
	}

	@Column(name = "parameter8", length = 50)
	public String getParameter8() {
		return this.parameter8;
	}

	public void setParameter8(String parameter8) {
		this.parameter8 = parameter8;
	}

	@Column(name = "parameter9", length = 50)
	public String getParameter9() {
		return this.parameter9;
	}

	public void setParameter9(String parameter9) {
		this.parameter9 = parameter9;
	}

	@Column(name = "parameter10", length = 50)
	public String getParameter10() {
		return this.parameter10;
	}

	public void setParameter10(String parameter10) {
		this.parameter10 = parameter10;
	}

}
