package com.health.model;
// Generated 2017-4-6 17:32:02 by Hibernate Tools 5.1.0.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * ThCommonDiagnosisResult generated by hbm2java
 */
@Entity
@Table(name = "th_common_diagnosis_result", catalog = "health")
public class ThCommonDiagnosisResult implements java.io.Serializable {

	private Long id;
	private String result;
	private Long count;

	public ThCommonDiagnosisResult() {
	}

	public ThCommonDiagnosisResult(String result, Long count) {
		this.result = result;
		this.count = count;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "result")
	public String getResult() {
		return this.result;
	}

	public void setResult(String result) {
		this.result = result;
	}

	@Column(name = "count")
	public Long getCount() {
		return this.count;
	}

	public void setCount(Long count) {
		this.count = count;
	}

}
