package com.health.model;
// Generated 2017-2-13 10:27:26 by Hibernate Tools 5.0.2.Final

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.springframework.format.annotation.DateTimeFormat;

/**
 * ThDevice generated by hbm2java
 */
@Entity
@Table(name = "th_device", catalog = "health")
public class ThDevice implements java.io.Serializable {

	private String deviceId;
	private String deviceType;
	private String deviceName;
	@DateTimeFormat(pattern="yyyy-MM-dd HH:mm:ss")
	private Date connectTime;
	@DateTimeFormat(pattern="yyyy-MM-dd HH:mm:ss")
	private Date transportTime;
	private Integer bluetoothSupport;
	private Integer microUsbsupport;
	private Integer usbTypeCsupport;
	private Date createTime;
	private Date updateTime;
	private String createUser;
	private String updateUser;
	private String sn;
	private String deviceStatus;
	private String mac;
	private String imei;

	public ThDevice() {
	}

	public ThDevice(String deviceId) {
		this.deviceId = deviceId;
	}

	public ThDevice(String deviceId, String deviceType, String deviceName, Date connectTime, Date transportTime,
			Integer bluetoothSupport, Integer microUsbsupport, Integer usbTypeCsupport, Date createTime,
			Date updateTime, String createUser, String updateUser, String sn, String deviceStatus, String mac,
			String imei) {
		this.deviceId = deviceId;
		this.deviceType = deviceType;
		this.deviceName = deviceName;
		this.connectTime = connectTime;
		this.transportTime = transportTime;
		this.bluetoothSupport = bluetoothSupport;
		this.microUsbsupport = microUsbsupport;
		this.usbTypeCsupport = usbTypeCsupport;
		this.createTime = createTime;
		this.updateTime = updateTime;
		this.createUser = createUser;
		this.updateUser = updateUser;
		this.sn = sn;
		this.deviceStatus = deviceStatus;
		this.mac = mac;
		this.imei = imei;
	}

	@Id

	@Column(name = "deviceId", unique = true, nullable = false, length = 45)
	public String getDeviceId() {
		return this.deviceId;
	}

	public void setDeviceId(String deviceId) {
		this.deviceId = deviceId;
	}

	@Column(name = "deviceType", length = 45)
	public String getDeviceType() {
		return this.deviceType;
	}

	public void setDeviceType(String deviceType) {
		this.deviceType = deviceType;
	}

	@Column(name = "deviceName", length = 45)
	public String getDeviceName() {
		return this.deviceName;
	}

	public void setDeviceName(String deviceName) {
		this.deviceName = deviceName;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "connectTime", length = 19)
	public Date getConnectTime() {
		return this.connectTime;
	}

	public void setConnectTime(Date connectTime) {
		this.connectTime = connectTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "transportTime", length = 19)
	public Date getTransportTime() {
		return this.transportTime;
	}

	public void setTransportTime(Date transportTime) {
		this.transportTime = transportTime;
	}

	@Column(name = "bluetoothSupport")
	public Integer getBluetoothSupport() {
		return this.bluetoothSupport;
	}

	public void setBluetoothSupport(Integer bluetoothSupport) {
		this.bluetoothSupport = bluetoothSupport;
	}

	@Column(name = "microUSBSupport")
	public Integer getMicroUsbsupport() {
		return this.microUsbsupport;
	}

	public void setMicroUsbsupport(Integer microUsbsupport) {
		this.microUsbsupport = microUsbsupport;
	}

	@Column(name = "usbTypeCSupport")
	public Integer getUsbTypeCsupport() {
		return this.usbTypeCsupport;
	}

	public void setUsbTypeCsupport(Integer usbTypeCsupport) {
		this.usbTypeCsupport = usbTypeCsupport;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "createTime", length = 19)
	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updateTime", length = 19)
	public Date getUpdateTime() {
		return this.updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	@Column(name = "createUser", length = 45)
	public String getCreateUser() {
		return this.createUser;
	}

	public void setCreateUser(String createUser) {
		this.createUser = createUser;
	}

	@Column(name = "updateUser", length = 45)
	public String getUpdateUser() {
		return this.updateUser;
	}

	public void setUpdateUser(String updateUser) {
		this.updateUser = updateUser;
	}

	@Column(name = "sn", length = 45)
	public String getSn() {
		return this.sn;
	}

	public void setSn(String sn) {
		this.sn = sn;
	}

	@Column(name = "device_status", length = 45)
	public String getDeviceStatus() {
		return this.deviceStatus;
	}

	public void setDeviceStatus(String deviceStatus) {
		this.deviceStatus = deviceStatus;
	}

	@Column(name = "mac", length = 45)
	public String getMac() {
		return this.mac;
	}

	public void setMac(String mac) {
		this.mac = mac;
	}

	@Column(name = "imei", length = 45)
	public String getImei() {
		return this.imei;
	}

	public void setImei(String imei) {
		this.imei = imei;
	}

}
