package com.health.model;
// Generated 2017-2-13 10:27:26 by Hibernate Tools 5.0.2.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ThDocument generated by hbm2java
 */
@Entity
@Table(name = "th_document", catalog = "health")
public class ThDocument implements java.io.Serializable {

	private Integer documentId;
	private String userId;
	private String name;
	private Integer documentType;
	private String healthTip;
	private Date createTime;
	private Date updateTime;
	private String createUser;
	private String updateUser;
	private String quotaNames;

	public ThDocument() {
	}

	public ThDocument(String userId, String name, Integer documentType, String healthTip, Date createTime,
			Date updateTime, String createUser, String updateUser) {
		this.userId = userId;
		this.name = name;
		this.documentType = documentType;
		this.healthTip = healthTip;
		this.createTime = createTime;
		this.updateTime = updateTime;
		this.createUser = createUser;
		this.updateUser = updateUser;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "documentId", unique = true, nullable = false)
	public Integer getDocumentId() {
		return this.documentId;
	}

	public void setDocumentId(Integer documentId) {
		this.documentId = documentId;
	}

	@Column(name = "userId", length = 50)
	public String getUserId() {
		return this.userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	@Column(name = "name", length = 45)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "documentType")
	public Integer getDocumentType() {
		return this.documentType;
	}

	public void setDocumentType(Integer documentType) {
		this.documentType = documentType;
	}

	@Column(name = "healthTip", length = 300)
	public String getHealthTip() {
		return this.healthTip;
	}

	public void setHealthTip(String healthTip) {
		this.healthTip = healthTip;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "createTime", length = 19)
	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updateTime", length = 19)
	public Date getUpdateTime() {
		return this.updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	@Column(name = "createUser", length = 45)
	public String getCreateUser() {
		return this.createUser;
	}

	public void setCreateUser(String createUser) {
		this.createUser = createUser;
	}

	@Column(name = "updateUser", length = 45)
	public String getUpdateUser() {
		return this.updateUser;
	}

	public void setUpdateUser(String updateUser) {
		this.updateUser = updateUser;
	}
	
	@Column(name = "quotaNames", length = 100)
	public String getQuotaNames() {
		return this.quotaNames;
	}

	public void setQuotaNames(String quotaNames) {
		this.quotaNames = quotaNames;
	}

}
