package com.health.model;
// Generated 2017-2-15 15:54:26 by Hibernate Tools 5.0.2.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ThDocumentQuota generated by hbm2java
 */
@Entity
@Table(name = "th_document_quota", catalog = "health")
public class ThDocumentQuota implements java.io.Serializable {

	private Integer documentQuotaId;
	private Integer documentId;
	private Integer quotaRecordId;
	private String quotaName;
	private Date createTime;
	private String createUser;

	public ThDocumentQuota() {
	}

	public ThDocumentQuota(Integer documentId, Integer quotaId, Date createTime, String createUser) {
		this.documentId = documentId;
		this.quotaRecordId = quotaRecordId;
		this.createTime = createTime;
		this.createUser = createUser;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "documentQuotaId", unique = true, nullable = false)
	public Integer getDocumentQuotaId() {
		return this.documentQuotaId;
	}

	public void setDocumentQuotaId(Integer documentQuotaId) {
		this.documentQuotaId = documentQuotaId;
	}

	@Column(name = "documentId")
	public Integer getDocumentId() {
		return this.documentId;
	}

	public void setDocumentId(Integer documentId) {
		this.documentId = documentId;
	}

	@Column(name = "quotaRecordId")
	public Integer getQuotaRecordId() {
		return this.quotaRecordId;
	}

	public void setQuotaRecordId(Integer quotaRecordId) {
		this.quotaRecordId = quotaRecordId;
	}
	
	@Column(name = "quotaName", length = 45)
	public String getQuotaName() {
		return this.quotaName;
	}

	public void setQuotaName(String quotaName) {
		this.quotaName = quotaName;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "createTime", length = 19)
	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	@Column(name = "createUser", length = 45)
	public String getCreateUser() {
		return this.createUser;
	}

	public void setCreateUser(String createUser) {
		this.createUser = createUser;
	}

}
