package com.health.model;
// Generated 2017-1-20 10:46:12 by Hibernate Tools 5.0.2.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ThFat generated by hbm2java
 */
@Entity
@Table(name = "th_fat", catalog = "health")
public class ThFat implements java.io.Serializable {

	private Integer fatId;
	private String userId;
	private Integer fatType;
	private Double bmi;
	private Double bfr;
	private Double muscleMass;
	private Double moisture;
	private Double boneMass;
	private Double bmr;
	private Double visceralFat;
	private String equipment;
	private Date createTime;
	private String createUser;
	private Date updateTime;
	private String updateUser;

	public ThFat() {
	}

	public ThFat(String userId, Integer fatType, Double bmi, Double bfr, Double muscleMass, Double moisture,
			Double boneMass, Double bmr, Double visceralFat, String equipment, Date createTime, String createUser,
			Date updateTime, String updateUser) {
		this.userId = userId;
		this.fatType = fatType;
		this.bmi = bmi;
		this.bfr = bfr;
		this.muscleMass = muscleMass;
		this.moisture = moisture;
		this.boneMass = boneMass;
		this.bmr = bmr;
		this.visceralFat = visceralFat;
		this.equipment = equipment;
		this.createTime = createTime;
		this.createUser = createUser;
		this.updateTime = updateTime;
		this.updateUser = updateUser;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "fatId", unique = true, nullable = false)
	public Integer getFatId() {
		return this.fatId;
	}

	public void setFatId(Integer fatId) {
		this.fatId = fatId;
	}

	@Column(name = "userId", length = 50)
	public String getUserId() {
		return this.userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	@Column(name = "fatType")
	public Integer getFatType() {
		return this.fatType;
	}

	public void setFatType(Integer fatType) {
		this.fatType = fatType;
	}

	@Column(name = "BMI", precision = 22, scale = 0)
	public Double getBmi() {
		return this.bmi;
	}

	public void setBmi(Double bmi) {
		this.bmi = bmi;
	}

	@Column(name = "BFR", precision = 22, scale = 0)
	public Double getBfr() {
		return this.bfr;
	}

	public void setBfr(Double bfr) {
		this.bfr = bfr;
	}

	@Column(name = "muscleMass", precision = 22, scale = 0)
	public Double getMuscleMass() {
		return this.muscleMass;
	}

	public void setMuscleMass(Double muscleMass) {
		this.muscleMass = muscleMass;
	}

	@Column(name = "moisture", precision = 22, scale = 0)
	public Double getMoisture() {
		return this.moisture;
	}

	public void setMoisture(Double moisture) {
		this.moisture = moisture;
	}

	@Column(name = "boneMass", precision = 22, scale = 0)
	public Double getBoneMass() {
		return this.boneMass;
	}

	public void setBoneMass(Double boneMass) {
		this.boneMass = boneMass;
	}

	@Column(name = "BMR", precision = 22, scale = 0)
	public Double getBmr() {
		return this.bmr;
	}

	public void setBmr(Double bmr) {
		this.bmr = bmr;
	}

	@Column(name = "visceralFat", precision = 22, scale = 0)
	public Double getVisceralFat() {
		return this.visceralFat;
	}

	public void setVisceralFat(Double visceralFat) {
		this.visceralFat = visceralFat;
	}

	@Column(name = "equipment", length = 60)
	public String getEquipment() {
		return this.equipment;
	}

	public void setEquipment(String equipment) {
		this.equipment = equipment;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "createTime", length = 19)
	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	@Column(name = "createUser", length = 45)
	public String getCreateUser() {
		return this.createUser;
	}

	public void setCreateUser(String createUser) {
		this.createUser = createUser;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updateTime", length = 19)
	public Date getUpdateTime() {
		return this.updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	@Column(name = "updateUser", length = 45)
	public String getUpdateUser() {
		return this.updateUser;
	}

	public void setUpdateUser(String updateUser) {
		this.updateUser = updateUser;
	}

}
