package com.health.model;
// Generated 2017-3-8 15:33:45 by Hibernate Tools 5.1.0.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ThGraphTemp generated by hbm2java
 */
@Entity
@Table(name = "th_graph_temp", catalog = "health")
public class ThGraphTemp implements java.io.Serializable {

	private Integer id;
	private String quotaName;
	private Double diff;
	private String source;
	private String target;
	private Date compareStartTime;
	private Date compareEndTime;
	private Date createTime;
	private Date updateTime;
	private String createUser;
	private String updateUser;

	public ThGraphTemp() {
	}

	public ThGraphTemp(Integer id) {
		this.id = id;
	}

	public ThGraphTemp(Integer id, String quotaName, Double diff, String source, String target, Date compareStartTime,
			Date compareEndTime, Date createTime, Date updateTime, String createUser, String updateUser) {
		this.id = id;
		this.quotaName = quotaName;
		this.diff = diff;
		this.source = source;
		this.target = target;
		this.compareStartTime = compareStartTime;
		this.compareEndTime = compareEndTime;
		this.createTime = createTime;
		this.updateTime = updateTime;
		this.createUser = createUser;
		this.updateUser = updateUser;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "quotaName", length = 45)
	public String getQuotaName() {
		return this.quotaName;
	}

	public void setQuotaName(String quotaName) {
		this.quotaName = quotaName;
	}

	@Column(name = "diff", precision = 22, scale = 0)
	public Double getDiff() {
		return this.diff;
	}

	public void setDiff(Double diff) {
		this.diff = diff;
	}

	@Column(name = "source", length = 45)
	public String getSource() {
		return this.source;
	}

	public void setSource(String source) {
		this.source = source;
	}

	@Column(name = "target", length = 45)
	public String getTarget() {
		return this.target;
	}

	public void setTarget(String target) {
		this.target = target;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "compareStartTime", length = 19)
	public Date getCompareStartTime() {
		return this.compareStartTime;
	}

	public void setCompareStartTime(Date compareStartTime) {
		this.compareStartTime = compareStartTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "compareEndTime", length = 19)
	public Date getCompareEndTime() {
		return this.compareEndTime;
	}

	public void setCompareEndTime(Date compareEndTime) {
		this.compareEndTime = compareEndTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "createTime", length = 19)
	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updateTime", length = 19)
	public Date getUpdateTime() {
		return this.updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	@Column(name = "createUser", length = 45)
	public String getCreateUser() {
		return this.createUser;
	}

	public void setCreateUser(String createUser) {
		this.createUser = createUser;
	}

	@Column(name = "updateUser", length = 45)
	public String getUpdateUser() {
		return this.updateUser;
	}

	public void setUpdateUser(String updateUser) {
		this.updateUser = updateUser;
	}

}
