package com.health.model;
// Generated 2017-2-13 10:27:26 by Hibernate Tools 5.0.2.Final

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.springframework.format.annotation.DateTimeFormat;

/**
 * ThInjuryHistory generated by hbm2java
 */
@Entity
@Table(name = "th_history_injury", catalog = "health")
public class ThHistoryInjury implements java.io.Serializable {

	private String id;
	private String injuryName;
	@DateTimeFormat(pattern="yyyy-MM-dd HH:mm:ss")
	private Date injuryTime;
	private String injuryDescription;
	private Date createTime;
	private Date updateTime;
	private String createUser;
	private String updateUser;
	private String userId;

	public ThHistoryInjury() {
	}

	public ThHistoryInjury(String id) {
		this.id = id;
	}

	public ThHistoryInjury(String id, String injuryName, Date injuryTime, String injuryDescription, Date createTime,
			Date updateTime, String createUser, String updateUser, String userId) {
		this.id = id;
		this.injuryName = injuryName;
		this.injuryTime = injuryTime;
		this.injuryDescription = injuryDescription;
		this.createTime = createTime;
		this.updateTime = updateTime;
		this.createUser = createUser;
		this.updateUser = updateUser;
		this.userId = userId;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false, length = 45)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@Column(name = "injuryName", length = 45)
	public String getInjuryName() {
		return this.injuryName;
	}

	public void setInjuryName(String injuryName) {
		this.injuryName = injuryName;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "injuryTime", length = 19)
	public Date getInjuryTime() {
		return this.injuryTime;
	}

	public void setInjuryTime(Date injuryTime) {
		this.injuryTime = injuryTime;
	}

	@Column(name = "injuryDescription", length = 45)
	public String getInjuryDescription() {
		return this.injuryDescription;
	}

	public void setInjuryDescription(String injuryDescription) {
		this.injuryDescription = injuryDescription;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "createTime", length = 19)
	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updateTime", length = 19)
	public Date getUpdateTime() {
		return this.updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	@Column(name = "createUser", length = 45)
	public String getCreateUser() {
		return this.createUser;
	}

	public void setCreateUser(String createUser) {
		this.createUser = createUser;
	}

	@Column(name = "updateUser", length = 45)
	public String getUpdateUser() {
		return this.updateUser;
	}

	public void setUpdateUser(String updateUser) {
		this.updateUser = updateUser;
	}

	@Column(name = "userId", length = 45)
	public String getUserId() {
		return this.userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

}
