package com.health.model;
// Generated 2017-2-13 10:27:26 by Hibernate Tools 5.0.2.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ThHistoryPharmacy generated by hbm2java
 */
@Entity
@Table(name = "th_history_pharmacy", catalog = "health")
public class ThHistoryPharmacy implements java.io.Serializable {

	private String id;
	private String medicalName;
	private String way;
	private String dosage;
	private String drugDependence;
	private String medicationTime;
	private Date createTime;
	private Date updateTime;
	private String createUser;
	private String updateUser;
	private String userId;

	public ThHistoryPharmacy() {
	}

	public ThHistoryPharmacy(String id) {
		this.id = id;
	}

	public ThHistoryPharmacy(String id, String medicalName, String way, String dosage, String drugDependence,
			String medicationTime, Date createTime, Date updateTime, String createUser, String updateUser,
			String userId) {
		this.id = id;
		this.medicalName = medicalName;
		this.way = way;
		this.dosage = dosage;
		this.drugDependence = drugDependence;
		this.medicationTime = medicationTime;
		this.createTime = createTime;
		this.updateTime = updateTime;
		this.createUser = createUser;
		this.updateUser = updateUser;
		this.userId = userId;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false, length = 45)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@Column(name = "medicalName", length = 45)
	public String getMedicalName() {
		return this.medicalName;
	}

	public void setMedicalName(String medicalName) {
		this.medicalName = medicalName;
	}

	@Column(name = "way", length = 45)
	public String getWay() {
		return this.way;
	}

	public void setWay(String way) {
		this.way = way;
	}

	@Column(name = "dosage", length = 45)
	public String getDosage() {
		return this.dosage;
	}

	public void setDosage(String dosage) {
		this.dosage = dosage;
	}

	@Column(name = "drugDependence", length = 45)
	public String getDrugDependence() {
		return this.drugDependence;
	}

	public void setDrugDependence(String drugDependence) {
		this.drugDependence = drugDependence;
	}

	@Column(name = "medicationTime", length = 45)
	public String getMedicationTime() {
		return this.medicationTime;
	}

	public void setMedicationTime(String medicationTime) {
		this.medicationTime = medicationTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "createTime", length = 19)
	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updateTime", length = 19)
	public Date getUpdateTime() {
		return this.updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	@Column(name = "createUser", length = 45)
	public String getCreateUser() {
		return this.createUser;
	}

	public void setCreateUser(String createUser) {
		this.createUser = createUser;
	}

	@Column(name = "updateUser", length = 45)
	public String getUpdateUser() {
		return this.updateUser;
	}

	public void setUpdateUser(String updateUser) {
		this.updateUser = updateUser;
	}

	@Column(name = "userId", length = 45)
	public String getUserId() {
		return this.userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

}
