package com.health.model;
// Generated 2017-2-13 10:27:26 by Hibernate Tools 5.0.2.Final

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.springframework.format.annotation.DateTimeFormat;

/**
 * ThHistoryHospitalized generated by hbm2java
 */
@Entity
@Table(name = "th_history_hospitalized", catalog = "health")
public class ThHistoryHospitalized implements java.io.Serializable {

	private String id;
	private String patientId;
	private String institution;
	private String cause;
	@DateTimeFormat(pattern="yyyy-MM-dd HH:mm:ss")
	private Date hospitalInTime;
	@DateTimeFormat(pattern="yyyy-MM-dd HH:mm:ss")
	private Date hospitalOutTime;
	private String bedId;
	private String bedInstitution;
	@DateTimeFormat(pattern="yyyy-MM-dd HH:mm:ss")
	private Date bedCreateTime;
	@DateTimeFormat(pattern="yyyy-MM-dd HH:mm:ss")
	private Date bedDelTime;
	private Date createTime;
	private Date updateTime;
	private String createUser;
	private String updateUser;
	private String userId;

	public ThHistoryHospitalized() {
	}

	public ThHistoryHospitalized(String id) {
		this.id = id;
	}

	public ThHistoryHospitalized(String id, String patientId, String institution, String cause, Date hospitalInTime,
			Date hospitalOutTime, String bedId, String bedInstitution, Date bedCreateTime, Date bedDelTime,
			Date createTime, Date updateTime, String createUser, String updateUser, String userId) {
		this.id = id;
		this.patientId = patientId;
		this.institution = institution;
		this.cause = cause;
		this.hospitalInTime = hospitalInTime;
		this.hospitalOutTime = hospitalOutTime;
		this.bedId = bedId;
		this.bedInstitution = bedInstitution;
		this.bedCreateTime = bedCreateTime;
		this.bedDelTime = bedDelTime;
		this.createTime = createTime;
		this.updateTime = updateTime;
		this.createUser = createUser;
		this.updateUser = updateUser;
		this.userId = userId;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false, length = 45)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@Column(name = "patientId", length = 45)
	public String getPatientId() {
		return this.patientId;
	}

	public void setPatientId(String patientId) {
		this.patientId = patientId;
	}

	@Column(name = "institution", length = 45)
	public String getInstitution() {
		return this.institution;
	}

	public void setInstitution(String institution) {
		this.institution = institution;
	}

	@Column(name = "cause", length = 45)
	public String getCause() {
		return this.cause;
	}

	public void setCause(String cause) {
		this.cause = cause;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "hospitalInTime", length = 19)
	public Date getHospitalInTime() {
		return this.hospitalInTime;
	}

	public void setHospitalInTime(Date hospitalInTime) {
		this.hospitalInTime = hospitalInTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "hospitalOutTime", length = 19)
	public Date getHospitalOutTime() {
		return this.hospitalOutTime;
	}

	public void setHospitalOutTime(Date hospitalOutTime) {
		this.hospitalOutTime = hospitalOutTime;
	}

	@Column(name = "bedId", length = 45)
	public String getBedId() {
		return this.bedId;
	}

	public void setBedId(String bedId) {
		this.bedId = bedId;
	}

	@Column(name = "bedInstitution", length = 45)
	public String getBedInstitution() {
		return this.bedInstitution;
	}

	public void setBedInstitution(String bedInstitution) {
		this.bedInstitution = bedInstitution;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "bedCreateTime", length = 19)
	public Date getBedCreateTime() {
		return this.bedCreateTime;
	}

	public void setBedCreateTime(Date bedCreateTime) {
		this.bedCreateTime = bedCreateTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "bedDelTime", length = 19)
	public Date getBedDelTime() {
		return this.bedDelTime;
	}

	public void setBedDelTime(Date bedDelTime) {
		this.bedDelTime = bedDelTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "createTime", length = 19)
	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updateTime", length = 19)
	public Date getUpdateTime() {
		return this.updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	@Column(name = "createUser", length = 45)
	public String getCreateUser() {
		return this.createUser;
	}

	public void setCreateUser(String createUser) {
		this.createUser = createUser;
	}

	@Column(name = "updateUser", length = 45)
	public String getUpdateUser() {
		return this.updateUser;
	}

	public void setUpdateUser(String updateUser) {
		this.updateUser = updateUser;
	}

	@Column(name = "userId", length = 45)
	public String getUserId() {
		return this.userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

}
