package com.health.model;
// Generated 2017-2-13 10:27:26 by Hibernate Tools 5.0.2.Final

import java.util.Date;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * ThHistoryDisease generated by hbm2java
 */
@Entity
@Table(name = "th_history_disease", catalog = "health")
public class ThHistoryDisease implements java.io.Serializable {

	private String id;
	private String disease;
	private String diagnosisTime;
	private String iscured;
	private Date createTime;
	private Date updateTime;
	private String createUser;
	private String updateUser;
	private String userId;
	
	public ThHistoryDisease() {
	}

	public ThHistoryDisease(String id) {
		this.id = id;
	}

	public ThHistoryDisease(String id, String disease, String diagnosisTime, String iscured, Date createTime,
			Date updateTime, String createUser, String updateUser, String userId) {
		this.id = id;
		this.disease = disease;
		this.diagnosisTime = diagnosisTime;
		this.iscured = iscured;
		this.createTime = createTime;
		this.updateTime = updateTime;
		this.createUser = createUser;
		this.updateUser = updateUser;
		this.userId = userId;
	}
	
	@Id
	@Column(name = "id", unique = true, nullable = false, length = 45)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@Column(name = "disease", length = 45)
	public String getDisease() {
		return this.disease;
	}

	public void setDisease(String disease) {
		this.disease = disease;
	}

	@Column(name = "diagnosisTime", length = 45)
	public String getDiagnosisTime() {
		return this.diagnosisTime;
	}

	public void setDiagnosisTime(String diagnosisTime) {
		this.diagnosisTime = diagnosisTime;
	}

	@Column(name = "iscured", length = 45)
	public String getIscured() {
		return this.iscured;
	}

	public void setIscured(String iscured) {
		this.iscured = iscured;
	}

	@Column(name = "createTime", length = 19)
	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	@Column(name = "updateTime", length = 19)
	public Date getUpdateTime() {
		return this.updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	@Column(name = "createUser", length = 45)
	public String getCreateUser() {
		return this.createUser;
	}

	public void setCreateUser(String createUser) {
		this.createUser = createUser;
	}

	@Column(name = "updateUser", length = 45)
	public String getUpdateUser() {
		return this.updateUser;
	}

	public void setUpdateUser(String updateUser) {
		this.updateUser = updateUser;
	}

	@Column(name = "userId", length = 45)
	public String getUserId() {
		return this.userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}


}
