package com.health.model;
// Generated 2017-2-13 10:27:26 by Hibernate Tools 5.0.2.Final

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.springframework.format.annotation.DateTimeFormat;

/**
 * ThHistoryTransfusion generated by hbm2java
 */
@Entity
@Table(name = "th_history_transfusion", catalog = "health")
public class ThHistoryTransfusion implements java.io.Serializable {

	private String id;
	@DateTimeFormat(pattern="yyyy-MM-dd HH:mm:ss")
	private Date transfusionTime;
	private Integer bloodTransfusion;
	private String cause;
	private Date createTime;
	private Date updateTime;
	private String createUser;
	private String updateUser;
	private String userId;

	public ThHistoryTransfusion() {
	}

	public ThHistoryTransfusion(String id) {
		this.id = id;
	}

	public ThHistoryTransfusion(String id, Date transfusionTime, Integer bloodTransfusion, String cause,
			Date createTime, Date updateTime, String createUser, String updateUser, String userId) {
		this.id = id;
		this.transfusionTime = transfusionTime;
		this.bloodTransfusion = bloodTransfusion;
		this.cause = cause;
		this.createTime = createTime;
		this.updateTime = updateTime;
		this.createUser = createUser;
		this.updateUser = updateUser;
		this.userId = userId;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false, length = 45)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "transfusionTime", length = 19)
	public Date getTransfusionTime() {
		return this.transfusionTime;
	}

	public void setTransfusionTime(Date transfusionTime) {
		this.transfusionTime = transfusionTime;
	}

	@Column(name = "bloodTransfusion")
	public Integer getBloodTransfusion() {
		return this.bloodTransfusion;
	}

	public void setBloodTransfusion(Integer bloodTransfusion) {
		this.bloodTransfusion = bloodTransfusion;
	}

	@Column(name = "cause", length = 45)
	public String getCause() {
		return this.cause;
	}

	public void setCause(String cause) {
		this.cause = cause;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "createTime", length = 19)
	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updateTIme", length = 19)
	public Date getUpdateTime() {
		return this.updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	@Column(name = "createUser", length = 45)
	public String getCreateUser() {
		return this.createUser;
	}

	public void setCreateUser(String createUser) {
		this.createUser = createUser;
	}

	@Column(name = "updateUser", length = 45)
	public String getUpdateUser() {
		return this.updateUser;
	}

	public void setUpdateUser(String updateUser) {
		this.updateUser = updateUser;
	}

	@Column(name = "userId", length = 45)
	public String getUserId() {
		return this.userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

}
