package com.health.model;
// Generated 2017-2-13 10:27:26 by Hibernate Tools 5.0.2.Final

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.springframework.format.annotation.DateTimeFormat;

/**
 * ThHistoryOperation generated by hbm2java
 */
@Entity
@Table(name = "th_history_operation", catalog = "health")
public class ThHistoryOperation implements java.io.Serializable {

	private String id;
	private String operationName;
	@DateTimeFormat(pattern="yyyy-MM-dd HH:mm:ss")
	private Date operationTime;
	private String operationResult;
	private Date createTime;
	private Date updateTime;
	private String createUser;
	private String updateUser;
	private String userId;

	public ThHistoryOperation() {
	}

	public ThHistoryOperation(String id) {
		this.id = id;
	}

	public ThHistoryOperation(String id, String operationName, Date operationTime, String operationResult,
			Date createTime, Date updateTime, String createUser, String updateUser, String userId) {
		this.id = id;
		this.operationName = operationName;
		this.operationTime = operationTime;
		this.operationResult = operationResult;
		this.createTime = createTime;
		this.updateTime = updateTime;
		this.createUser = createUser;
		this.updateUser = updateUser;
		this.userId = userId;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false, length = 45)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@Column(name = "operationName", length = 45)
	public String getOperationName() {
		return this.operationName;
	}

	public void setOperationName(String operationName) {
		this.operationName = operationName;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "operationTime", length = 19)
	public Date getOperationTime() {
		return this.operationTime;
	}

	public void setOperationTime(Date operationTime) {
		this.operationTime = operationTime;
	}

	@Column(name = "operationResult", length = 45)
	public String getOperationResult() {
		return this.operationResult;
	}

	public void setOperationResult(String operationResult) {
		this.operationResult = operationResult;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "createTime", length = 19)
	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updateTime", length = 19)
	public Date getUpdateTime() {
		return this.updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	@Column(name = "createUser", length = 45)
	public String getCreateUser() {
		return this.createUser;
	}

	public void setCreateUser(String createUser) {
		this.createUser = createUser;
	}

	@Column(name = "updateUser", length = 45)
	public String getUpdateUser() {
		return this.updateUser;
	}

	public void setUpdateUser(String updateUser) {
		this.updateUser = updateUser;
	}

	@Column(name = "userId", length = 45)
	public String getUserId() {
		return this.userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

}
