package com.health.model;
// Generated 2017-2-13 10:27:26 by Hibernate Tools 5.0.2.Final

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.springframework.format.annotation.DateTimeFormat;

/**
 * ThHistoryImmunization generated by hbm2java
 */
@Entity
@Table(name = "th_history_immunization", catalog = "health")
public class ThHistoryImmunization implements java.io.Serializable {

	private String id;
	private String immunizationName;
	@DateTimeFormat(pattern="yyyy-MM-dd HH:mm:ss")
	private Date immunizationDate;
	private String immunizationInstitution;
	private Date createTime;
	private Date updateTime;
	private String createUser;
	private String updateUser;
	private String userId;

	public ThHistoryImmunization() {
	}

	public ThHistoryImmunization(String id) {
		this.id = id;
	}

	public ThHistoryImmunization(String id, String immunizationName, Date immunizationDate,
			String immunizationInstitution, Date createTime, Date updateTime, String createUser, String updateUser,
			String userId) {
		this.id = id;
		this.immunizationName = immunizationName;
		this.immunizationDate = immunizationDate;
		this.immunizationInstitution = immunizationInstitution;
		this.createTime = createTime;
		this.updateTime = updateTime;
		this.createUser = createUser;
		this.updateUser = updateUser;
		this.userId = userId;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false, length = 45)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@Column(name = "immunizationName", length = 45)
	public String getImmunizationName() {
		return this.immunizationName;
	}

	public void setImmunizationName(String immunizationName) {
		this.immunizationName = immunizationName;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "immunizationDate", length = 19)
	public Date getImmunizationDate() {
		return this.immunizationDate;
	}

	public void setImmunizationDate(Date immunizationDate) {
		this.immunizationDate = immunizationDate;
	}

	@Column(name = "immunizationInstitution", length = 45)
	public String getImmunizationInstitution() {
		return this.immunizationInstitution;
	}

	public void setImmunizationInstitution(String immunizationInstitution) {
		this.immunizationInstitution = immunizationInstitution;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "createTime", length = 19)
	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updateTime", length = 19)
	public Date getUpdateTime() {
		return this.updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	@Column(name = "createUser", length = 45)
	public String getCreateUser() {
		return this.createUser;
	}

	public void setCreateUser(String createUser) {
		this.createUser = createUser;
	}

	@Column(name = "updateUser", length = 45)
	public String getUpdateUser() {
		return this.updateUser;
	}

	public void setUpdateUser(String updateUser) {
		this.updateUser = updateUser;
	}

	@Column(name = "userId", length = 45)
	public String getUserId() {
		return this.userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

}
