package com.health.model;
// Generated 2017-2-15 15:54:26 by Hibernate Tools 5.0.2.Final

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;


/**
 * ThMenu generated by hbm2java
 */
@Entity
@Table(name = "th_menu", catalog = "health")
public class ThMenu implements java.io.Serializable {

	private Integer menuId;
	private Integer pid;
	private String menuName;
	private Integer typeId;
	private Integer isValid;
	private String createUser;
	private Date createTime;
	private String updateUser;
	private Date updateTime;
	private String url;
	/*与数据库无关的参数开始*/
	
	private List<ThMenu> adminMenuMenu2 = new ArrayList<ThMenu>();
	/*与数据库无关的参数结束*/
	
	@Transient
	public List<ThMenu> getAdminMenuMenu2() {
		return adminMenuMenu2;
	}

	public void setAdminMenuMenu2(List<ThMenu> adminMenuMenu2) {
		this.adminMenuMenu2 = adminMenuMenu2;
	}

	public ThMenu() {
	}

	public ThMenu(Integer pid, String menuName, Integer typeId, Integer isValid, String createUser, Date createTime,
			String updateUser, Date updateTime, String url) {
		this.pid = pid;
		this.menuName = menuName;
		this.typeId = typeId;
		this.isValid = isValid;
		this.createUser = createUser;
		this.createTime = createTime;
		this.updateUser = updateUser;
		this.updateTime = updateTime;
		this.url = url;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "menuId", unique = true, nullable = false)
	public Integer getMenuId() {
		return this.menuId;
	}

	public void setMenuId(Integer menuId) {
		this.menuId = menuId;
	}

	@Column(name = "pid")
	public Integer getPid() {
		return this.pid;
	}

	public void setPid(Integer pid) {
		this.pid = pid;
	}

	@Column(name = "menuName", length = 32)
	public String getMenuName() {
		return this.menuName;
	}

	public void setMenuName(String menuName) {
		this.menuName = menuName;
	}

	@Column(name = "typeId")
	public Integer getTypeId() {
		return this.typeId;
	}

	public void setTypeId(Integer typeId) {
		this.typeId = typeId;
	}

	@Column(name = "isValid")
	public Integer getIsValid() {
		return this.isValid;
	}

	public void setIsValid(Integer isValid) {
		this.isValid = isValid;
	}

	@Column(name = "createUser", length = 32)
	public String getCreateUser() {
		return this.createUser;
	}

	public void setCreateUser(String createUser) {
		this.createUser = createUser;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "createTime", length = 19)
	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	@Column(name = "updateUser", length = 32)
	public String getUpdateUser() {
		return this.updateUser;
	}

	public void setUpdateUser(String updateUser) {
		this.updateUser = updateUser;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updateTime", length = 19)
	public Date getUpdateTime() {
		return this.updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	@Column(name = "url")
	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

}
