package com.health.model;
// Generated 2017-2-13 10:27:26 by Hibernate Tools 5.0.2.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ThNotificationConfig generated by hbm2java
 */
@Entity
@Table(name = "th_notification_config", catalog = "health")
public class ThNotificationConfig implements java.io.Serializable {

	private Integer configId;
	private String userId;
	private String title;
	private Date allertTime;

	public ThNotificationConfig() {
	}

	public ThNotificationConfig(String userId, String title, Date allertTime) {
		this.userId = userId;
		this.title = title;
		this.allertTime = allertTime;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "configId", unique = true, nullable = false)
	public Integer getConfigId() {
		return this.configId;
	}

	public void setConfigId(Integer configId) {
		this.configId = configId;
	}

	@Column(name = "userId", length = 45)
	public String getUserId() {
		return this.userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	@Column(name = "title", length = 45)
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "allertTime", length = 19)
	public Date getAllertTime() {
		return this.allertTime;
	}

	public void setAllertTime(Date allertTime) {
		this.allertTime = allertTime;
	}

}
