package com.health.model;
// Generated 2017-2-15 15:54:26 by Hibernate Tools 5.0.2.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * ThOrganization generated by hbm2java
 */
@Entity
@Table(name = "th_organization", catalog = "health")
public class ThOrganization implements java.io.Serializable {

	private Integer organizationId;
	private String organizationName;
	private String organizationPosition;
	private String type;
	private String tel;
	private String fax;
	private String email;
	private String weChat;
	private String qqNum;
	private String organizationLogo;

	public ThOrganization() {
	}

	public ThOrganization(String organizationName) {
		this.organizationName = organizationName;
	}

	public ThOrganization(String organizationName, String organizationPosition, String type, String tel, String fax,
			String email, String weChat, String qqNum, String organizationLogo) {
		this.organizationName = organizationName;
		this.organizationPosition = organizationPosition;
		this.type = type;
		this.tel = tel;
		this.fax = fax;
		this.email = email;
		this.weChat = weChat;
		this.qqNum = qqNum;
		this.organizationLogo = organizationLogo;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "organizationId", unique = true, nullable = false)
	public Integer getOrganizationId() {
		return this.organizationId;
	}

	public void setOrganizationId(Integer organizationId) {
		this.organizationId = organizationId;
	}

	@Column(name = "organizationName", nullable = false, length = 50)
	public String getOrganizationName() {
		return this.organizationName;
	}

	public void setOrganizationName(String organizationName) {
		this.organizationName = organizationName;
	}

	@Column(name = "organizationPosition", length = 50)
	public String getOrganizationPosition() {
		return this.organizationPosition;
	}

	public void setOrganizationPosition(String organizationPosition) {
		this.organizationPosition = organizationPosition;
	}

	@Column(name = "type", length = 25)
	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	@Column(name = "tel", length = 48)
	public String getTel() {
		return this.tel;
	}

	public void setTel(String tel) {
		this.tel = tel;
	}

	@Column(name = "fax", length = 48)
	public String getFax() {
		return this.fax;
	}

	public void setFax(String fax) {
		this.fax = fax;
	}

	@Column(name = "email", length = 50)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "weChat", length = 49)
	public String getWeChat() {
		return this.weChat;
	}

	public void setWeChat(String weChat) {
		this.weChat = weChat;
	}

	@Column(name = "qqNum", length = 49)
	public String getQqNum() {
		return this.qqNum;
	}

	public void setQqNum(String qqNum) {
		this.qqNum = qqNum;
	}

	@Column(name = "organizationLogo", length = 1024)
	public String getOrganizationLogo() {
		return this.organizationLogo;
	}

	public void setOrganizationLogo(String organizationLogo) {
		this.organizationLogo = organizationLogo;
	}

	@Override
	public String toString() {
		return "ThOrganization [organizationId=" + organizationId + ", organizationName=" + organizationName
				+ ", organizationPosition=" + organizationPosition + ", type=" + type + ", tel=" + tel + ", fax=" + fax
				+ ", email=" + email + ", weChat=" + weChat + ", qqNum=" + qqNum + ", organizationLogo="
				+ organizationLogo + "]";
	}

}
