package com.health.model;
// Generated 2017-2-15 15:54:26 by Hibernate Tools 5.0.2.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ThQuotaStandard generated by hbm2java
 */
@Entity
@Table(name = "th_quota_standard", catalog = "health")
public class ThQuotaStandard implements java.io.Serializable {

	private Integer quotaStandardId;
	private Integer quotaId;
	private Integer gender;
	private Integer ageStart;
	private Integer ageEnd;
	private Double standardValue;
	private Date createTime;
	private String createUser;
	private Date updateTime;
	private String updateUser;

	public ThQuotaStandard() {
	}

	public ThQuotaStandard(Integer quotaId, Integer gender, Integer ageStart, Integer ageEnd, Double standardValue,
			Date createTime, String createUser, Date updateTime, String updateUser) {
		this.quotaId = quotaId;
		this.gender = gender;
		this.ageStart = ageStart;
		this.ageEnd = ageEnd;
		this.standardValue = standardValue;
		this.createTime = createTime;
		this.createUser = createUser;
		this.updateTime = updateTime;
		this.updateUser = updateUser;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "quotaStandardId", unique = true, nullable = false)
	public Integer getQuotaStandardId() {
		return this.quotaStandardId;
	}

	public void setQuotaStandardId(Integer quotaStandardId) {
		this.quotaStandardId = quotaStandardId;
	}

	@Column(name = "quotaId")
	public Integer getQuotaId() {
		return this.quotaId;
	}

	public void setQuotaId(Integer quotaId) {
		this.quotaId = quotaId;
	}

	@Column(name = "gender")
	public Integer getGender() {
		return this.gender;
	}

	public void setGender(Integer gender) {
		this.gender = gender;
	}

	@Column(name = "ageStart")
	public Integer getAgeStart() {
		return this.ageStart;
	}

	public void setAgeStart(Integer ageStart) {
		this.ageStart = ageStart;
	}

	@Column(name = "ageEnd")
	public Integer getAgeEnd() {
		return this.ageEnd;
	}

	public void setAgeEnd(Integer ageEnd) {
		this.ageEnd = ageEnd;
	}

	@Column(name = "standardValue", precision = 22, scale = 0)
	public Double getStandardValue() {
		return this.standardValue;
	}

	public void setStandardValue(Double standardValue) {
		this.standardValue = standardValue;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "createTime", length = 19)
	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	@Column(name = "createUser", length = 45)
	public String getCreateUser() {
		return this.createUser;
	}

	public void setCreateUser(String createUser) {
		this.createUser = createUser;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updateTime", length = 19)
	public Date getUpdateTime() {
		return this.updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	@Column(name = "updateUser", length = 45)
	public String getUpdateUser() {
		return this.updateUser;
	}

	public void setUpdateUser(String updateUser) {
		this.updateUser = updateUser;
	}

}
