package com.health.model;
// Generated 2017-2-15 15:54:26 by Hibernate Tools 5.0.2.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ThQuotaRecord generated by hbm2java
 */
@Entity
@Table(name = "th_quota_record", catalog = "health")
public class ThQuotaRecord implements java.io.Serializable {

	private Integer quotaRecordId;
	private String userId;
	private String userName;
	private Integer gender;
	private Integer userAge;
	private Integer quotaId;
	private Integer quotaType;
	private String quotaName;
	private String secondQuotaName;
	private Integer count;
	private Double value;
	private String unit;
	private String result;
	private Integer deviceId;
	private String device;
	private Integer organizationId;
	private Integer status;
	private Date createTime;
	private String createUser;
	private Date updateTime;
	private String updateUser;

	public ThQuotaRecord() {
	}

	public ThQuotaRecord(String userId, Integer quotaId, Double value, String unit, String result, Integer deviceId,
			String device, Date createTime, String createUser, Date updateTime, String updateUser) {
		this.userId = userId;
		this.quotaId = quotaId;
		this.value = value;
		this.unit = unit;
		this.result = result;
		this.deviceId = deviceId;
		this.device = device;
		this.createTime = createTime;
		this.createUser = createUser;
		this.updateTime = updateTime;
		this.updateUser = updateUser;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "quotaRecordId", unique = true, nullable = false)
	public Integer getQuotaRecordId() {
		return this.quotaRecordId;
	}

	public void setQuotaRecordId(Integer quotaRecordId) {
		this.quotaRecordId = quotaRecordId;
	}

	@Column(name = "userId", length = 45)
	public String getUserId() {
		return this.userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}
	
	@Column(name = "userName", length = 45)
	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}
	
	@Column(name = "gender")
	public Integer getGender() {
		return this.gender;
	}

	public void setGender(Integer gender) {
		this.gender = gender;
	}
	
	@Column(name = "userAge")
	public Integer getUserAge() {
		return this.userAge;
	}

	public void setUserAge(Integer userAge) {
		this.userAge = userAge;
	}

	@Column(name = "quotaId")
	public Integer getQuotaId() {
		return this.quotaId;
	}

	public void setQuotaId(Integer quotaId) {
		this.quotaId = quotaId;
	}
	
	@Column(name = "quotaType")
	public Integer getQuotaType() {
		return this.quotaType;
	}

	public void setQuotaType(Integer quotaType) {
		this.quotaType = quotaType;
	}
	
	@Column(name = "quotaName", length = 45)
	public String getQuotaName() {
		return this.quotaName;
	}

	public void setQuotaName(String quotaName) {
		this.quotaName = quotaName;
	}

	@Column(name = "secondQuotaName", length = 45)
	public String getSecondQuotaName() {
		return this.secondQuotaName;
	}

	public void setSecondQuotaName(String secondQuotaName) {
		this.secondQuotaName = secondQuotaName;
	}
	
	@Column(name = "count")
	public Integer getCount() {
		return this.count;
	}

	public void setCount(Integer count) {
		this.count = count;
	}
	
	@Column(name = "value", precision = 22, scale = 0)
	public Double getValue() {
		return this.value;
	}

	public void setValue(Double value) {
		this.value = value;
	}

	@Column(name = "unit", length = 45)
	public String getUnit() {
		return this.unit;
	}

	public void setUnit(String unit) {
		this.unit = unit;
	}

	@Column(name = "result", length = 45)
	public String getResult() {
		return this.result;
	}

	public void setResult(String result) {
		this.result = result;
	}

	@Column(name = "deviceId")
	public Integer getDeviceId() {
		return this.deviceId;
	}

	public void setDeviceId(Integer deviceId) {
		this.deviceId = deviceId;
	}

	@Column(name = "device", length = 45)
	public String getDevice() {
		return this.device;
	}

	public void setDevice(String device) {
		this.device = device;
	}
	
	@Column(name = "organizationId")
	public Integer getOrganizationId() {
		return this.organizationId;
	}

	public void setOrganizationId(Integer organizationId) {
		this.organizationId = organizationId;
	}
	
	@Column(name = "status")
	public Integer getStatus() {
		return this.status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "createTime", length = 19)
	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	@Column(name = "createUser", length = 45)
	public String getCreateUser() {
		return this.createUser;
	}

	public void setCreateUser(String createUser) {
		this.createUser = createUser;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updateTime", length = 19)
	public Date getUpdateTime() {
		return this.updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	@Column(name = "updateUser", length = 45)
	public String getUpdateUser() {
		return this.updateUser;
	}

	public void setUpdateUser(String updateUser) {
		this.updateUser = updateUser;
	}

	@Override
	public String toString() {
		return "ThQuotaRecord [quotaRecordId=" + quotaRecordId + ", userId=" + userId + ", userName=" + userName
				+ ", gender=" + gender + ", userAge=" + userAge + ", quotaId=" + quotaId + ", quotaType=" + quotaType
				+ ", quotaName=" + quotaName + ", secondQuotaName=" + secondQuotaName + ", count=" + count + ", value="
				+ value + ", unit=" + unit + ", result=" + result + ", deviceId=" + deviceId + ", device=" + device
				+ ", organizationId=" + organizationId + ", status=" + status + ", createTime=" + createTime
				+ ", createUser=" + createUser + ", updateTime=" + updateTime + ", updateUser=" + updateUser + "]";
	}

	
}
