package com.health.model;
// Generated 2017-2-15 15:54:26 by Hibernate Tools 5.0.2.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ThQuota generated by hbm2java
 */
@Entity
@Table(name = "th_quota", catalog = "health")
public class ThQuota implements java.io.Serializable {

	private Integer quotaId;
	private Integer quotaType;
	private String quotaName;
	private String secondQuotaName;
	private Date createTime;
	private String createUser;
	private Date updateTime;
	private String updateUser;
	private String remark;

	public ThQuota() {
	}

	public ThQuota(Integer quotaType, String quotaName, String secondQuotaName, Date createTime, String createUser,
			Date updateTime, String updateUser, String remark) {
		this.quotaType = quotaType;
		this.quotaName = quotaName;
		this.secondQuotaName = secondQuotaName;
		this.createTime = createTime;
		this.createUser = createUser;
		this.updateTime = updateTime;
		this.updateUser = updateUser;
		this.remark = remark;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "quotaId", unique = true, nullable = false)
	public Integer getQuotaId() {
		return this.quotaId;
	}

	public void setQuotaId(Integer quotaId) {
		this.quotaId = quotaId;
	}

	@Column(name = "quotaType")
	public Integer getQuotaType() {
		return this.quotaType;
	}

	public void setQuotaType(Integer quotaType) {
		this.quotaType = quotaType;
	}

	@Column(name = "quotaName", length = 45)
	public String getQuotaName() {
		return this.quotaName;
	}

	public void setQuotaName(String quotaName) {
		this.quotaName = quotaName;
	}

	@Column(name = "secondQuotaName", length = 45)
	public String getSecondQuotaName() {
		return this.secondQuotaName;
	}

	public void setSecondQuotaName(String secondQuotaName) {
		this.secondQuotaName = secondQuotaName;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "createTime", length = 19)
	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	@Column(name = "createUser", length = 45)
	public String getCreateUser() {
		return this.createUser;
	}

	public void setCreateUser(String createUser) {
		this.createUser = createUser;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updateTime", length = 19)
	public Date getUpdateTime() {
		return this.updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	@Column(name = "updateUser", length = 45)
	public String getUpdateUser() {
		return this.updateUser;
	}

	public void setUpdateUser(String updateUser) {
		this.updateUser = updateUser;
	}

	@Column(name = "remark", length = 45)
	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	@Override
	public String toString() {
		return "ThQuota [quotaId=" + quotaId + ", quotaType=" + quotaType + ", quotaName=" + quotaName
				+ ", secondQuotaName=" + secondQuotaName + ", createTime=" + createTime + ", createUser=" + createUser
				+ ", updateTime=" + updateTime + ", updateUser=" + updateUser + ", remark=" + remark + "]";
	}

}
