package com.health.model;
// Generated 2017-2-15 15:54:26 by Hibernate Tools 5.0.2.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * ThRole generated by hbm2java
 */
@Entity
@Table(name = "th_role", catalog = "health")
public class ThRole implements java.io.Serializable {

	private Integer roleId;
	private String roleName;
	private String roleDescribe;

	public ThRole() {
	}

	public ThRole(String roleName, String roleDescribe) {
		this.roleName = roleName;
		this.roleDescribe = roleDescribe;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "roleId", unique = true, nullable = false)
	public Integer getRoleId() {
		return this.roleId;
	}

	public void setRoleId(Integer roleId) {
		this.roleId = roleId;
	}

	@Column(name = "roleName", length = 50)
	public String getRoleName() {
		return this.roleName;
	}

	public void setRoleName(String roleName) {
		this.roleName = roleName;
	}

	@Column(name = "roleDescribe", length = 100)
	public String getRoleDescribe() {
		return this.roleDescribe;
	}

	public void setRoleDescribe(String roleDescribe) {
		this.roleDescribe = roleDescribe;
	}

}
