package com.health.model;
// Generated 2017-1-20 10:46:12 by Hibernate Tools 5.0.2.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ThUrine generated by hbm2java
 */
@Entity
@Table(name = "th_urine", catalog = "health")
public class ThUrine implements java.io.Serializable {

	private Integer urineId;
	private String userId;
	private Integer urineType;
	private Double leu;
	private Double nit;
	private Double ubg;
	private Double pro;
	private Double ph;
	private Double bld;
	private Double sg;
	private Double ket;
	private Double bil;
	private Double glu;
	private Double vc;
	private String equipment;
	private Date createTime;
	private String createUser;
	private Date updateTime;
	private String updateUser;

	public ThUrine() {
	}

	public ThUrine(String userId, Integer urineType, Double leu, Double nit, Double ubg, Double pro, Double ph,
			Double bld, Double sg, Double ket, Double bil, Double glu, Double vc, String equipment, Date createTime,
			String createUser, Date updateTime, String updateUser) {
		this.userId = userId;
		this.urineType = urineType;
		this.leu = leu;
		this.nit = nit;
		this.ubg = ubg;
		this.pro = pro;
		this.ph = ph;
		this.bld = bld;
		this.sg = sg;
		this.ket = ket;
		this.bil = bil;
		this.glu = glu;
		this.vc = vc;
		this.equipment = equipment;
		this.createTime = createTime;
		this.createUser = createUser;
		this.updateTime = updateTime;
		this.updateUser = updateUser;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "urineId", unique = true, nullable = false)
	public Integer getUrineId() {
		return this.urineId;
	}

	public void setUrineId(Integer urineId) {
		this.urineId = urineId;
	}

	@Column(name = "userId", length = 50)
	public String getUserId() {
		return this.userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	@Column(name = "urineType")
	public Integer getUrineType() {
		return this.urineType;
	}

	public void setUrineType(Integer urineType) {
		this.urineType = urineType;
	}

	@Column(name = "LEU", precision = 22, scale = 0)
	public Double getLeu() {
		return this.leu;
	}

	public void setLeu(Double leu) {
		this.leu = leu;
	}

	@Column(name = "NIT", precision = 22, scale = 0)
	public Double getNit() {
		return this.nit;
	}

	public void setNit(Double nit) {
		this.nit = nit;
	}

	@Column(name = "UBG", precision = 22, scale = 0)
	public Double getUbg() {
		return this.ubg;
	}

	public void setUbg(Double ubg) {
		this.ubg = ubg;
	}

	@Column(name = "PRO", precision = 22, scale = 0)
	public Double getPro() {
		return this.pro;
	}

	public void setPro(Double pro) {
		this.pro = pro;
	}

	@Column(name = "PH", precision = 22, scale = 0)
	public Double getPh() {
		return this.ph;
	}

	public void setPh(Double ph) {
		this.ph = ph;
	}

	@Column(name = "BLD", precision = 22, scale = 0)
	public Double getBld() {
		return this.bld;
	}

	public void setBld(Double bld) {
		this.bld = bld;
	}

	@Column(name = "SG", precision = 22, scale = 0)
	public Double getSg() {
		return this.sg;
	}

	public void setSg(Double sg) {
		this.sg = sg;
	}

	@Column(name = "KET", precision = 22, scale = 0)
	public Double getKet() {
		return this.ket;
	}

	public void setKet(Double ket) {
		this.ket = ket;
	}

	@Column(name = "BIL", precision = 22, scale = 0)
	public Double getBil() {
		return this.bil;
	}

	public void setBil(Double bil) {
		this.bil = bil;
	}

	@Column(name = "GLU", precision = 22, scale = 0)
	public Double getGlu() {
		return this.glu;
	}

	public void setGlu(Double glu) {
		this.glu = glu;
	}

	@Column(name = "VC", precision = 22, scale = 0)
	public Double getVc() {
		return this.vc;
	}

	public void setVc(Double vc) {
		this.vc = vc;
	}

	@Column(name = "equipment", length = 60)
	public String getEquipment() {
		return this.equipment;
	}

	public void setEquipment(String equipment) {
		this.equipment = equipment;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "createTime", length = 19)
	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	@Column(name = "createUser", length = 45)
	public String getCreateUser() {
		return this.createUser;
	}

	public void setCreateUser(String createUser) {
		this.createUser = createUser;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updateTime", length = 19)
	public Date getUpdateTime() {
		return this.updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	@Column(name = "updateUser", length = 45)
	public String getUpdateUser() {
		return this.updateUser;
	}

	public void setUpdateUser(String updateUser) {
		this.updateUser = updateUser;
	}

}
