package com.health.model;
// Generated 2017-1-20 10:46:12 by Hibernate Tools 5.0.2.Final


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ThUserAddress generated by hbm2java
 */
@Entity
@Table(name="th_user_address"
    ,catalog="health"
)
public class ThUserAddress  implements java.io.Serializable {


     private Integer addressId;
     private String userId;
     private String name;
     private String tel;
     private String province;
     private String city;
     private String district;
     private String detailAddress;
     private String zipCode;
     private Date createTime;
 	 private String createUser;
 	 private Date updateTime;
 	 private String updateUser;
     
    public ThUserAddress() {
    }

    public ThUserAddress(String userId, String name, String tel, String province, String city, String district, String detailAddress, String zipCode, Date createTime, String createUser,
			Date updateTime, String updateUser) {
       this.userId = userId;
       this.name = name;
       this.tel = tel;
       this.province = province;
       this.city = city;
       this.district = district;
       this.detailAddress = detailAddress;
       this.zipCode = zipCode;
       this.createTime = createTime;
       this.createUser = createUser;
       this.updateTime = updateTime;
       this.updateUser = updateUser;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="addressId", unique=true, nullable=false)
    public Integer getAddressId() {
        return this.addressId;
    }
    
    public void setAddressId(Integer addressId) {
        this.addressId = addressId;
    }

    
    @Column(name="userId", length=50)
    public String getUserId() {
        return this.userId;
    }
    
    public void setUserId(String userId) {
        this.userId = userId;
    }

    
    @Column(name="name", length=45)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="tel", length=45)
    public String getTel() {
        return this.tel;
    }
    
    public void setTel(String tel) {
        this.tel = tel;
    }

    
    @Column(name="province", length=45)
    public String getProvince() {
        return this.province;
    }
    
    public void setProvince(String province) {
        this.province = province;
    }

    
    @Column(name="city", length=45)
    public String getCity() {
        return this.city;
    }
    
    public void setCity(String city) {
        this.city = city;
    }

    
    @Column(name="district", length=45)
    public String getDistrict() {
        return this.district;
    }
    
    public void setDistrict(String district) {
        this.district = district;
    }

    
    @Column(name="detailAddress", length=100)
    public String getDetailAddress() {
        return this.detailAddress;
    }
    
    public void setDetailAddress(String detailAddress) {
        this.detailAddress = detailAddress;
    }

    
    @Column(name="zipCode", length=45)
    public String getZipCode() {
        return this.zipCode;
    }
    
    public void setZipCode(String zipCode) {
        this.zipCode = zipCode;
    }
    
    @Temporal(TemporalType.TIMESTAMP)
	@Column(name = "createTime", length = 19)
	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	@Column(name = "createUser", length = 45)
	public String getCreateUser() {
		return this.createUser;
	}

	public void setCreateUser(String createUser) {
		this.createUser = createUser;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updateTime", length = 19)
	public Date getUpdateTime() {
		return this.updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	@Column(name = "updateUser", length = 45)
	public String getUpdateUser() {
		return this.updateUser;
	}

	public void setUpdateUser(String updateUser) {
		this.updateUser = updateUser;
	}

	@Override
	public String toString() {
		return "ThUserAddress [addressId=" + addressId + ", userId=" + userId + ", name=" + name + ", tel=" + tel
				+ ", province=" + province + ", city=" + city + ", district=" + district + ", detailAddress="
				+ detailAddress + ", zipCode=" + zipCode + ", createTime=" + createTime + ", createUser=" + createUser
				+ ", updateTime=" + updateTime + ", updateUser=" + updateUser + "]";
	}



}


