package com.health.model;
// Generated 2017-2-16 17:03:00 by Hibernate Tools 5.1.0.Final

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.springframework.format.annotation.DateTimeFormat;

/**
 * ThUserInfo generated by hbm2java
 */
@Entity
@Table(name = "th_user_info", catalog = "health")
public class ThUserInfo implements java.io.Serializable {

	private String id;
	private String headPortrait;
	private String nationality;
	private String village;
	private String nation;
	private String weight;
	private String bloodType;
	private String education;
	private String residentType;
	private String emergencyContact;
	private String workUnit;
	private String gender;
	@DateTimeFormat(pattern="yyyy-MM-dd HH:mm:ss")
	private Date birthday;
	private String nativePlace;
	private String neighborhoodCommittee;
	private String height;
	private String step;
	private String rh;
	private String maritalStatus;
	private String address;
	private String emergencyPerson;
	private String occupation;
	private String userId;
	private Date createTime;
	private Date updateTime;
	private String createUser;
	private String updateUser;

	public ThUserInfo() {
	}

	public ThUserInfo(String id) {
		this.id = id;
	}

	public ThUserInfo(String id, String headPortrait, String nationality, String village, String nation, String weight,
			String bloodType, String education, String residentType, String emergencyContact, String workUnit,
			String gender, Date birthday, String nativePlace, String neighborhoodCommittee, String height, String step,
			String rh, String maritalStatus, String address, String emergencyPerson, String occupation, String userId,
			Date createTime, Date updateTime, String createUser, String updateUser) {
		this.id = id;
		this.headPortrait = headPortrait;
		this.nationality = nationality;
		this.village = village;
		this.nation = nation;
		this.weight = weight;
		this.bloodType = bloodType;
		this.education = education;
		this.residentType = residentType;
		this.emergencyContact = emergencyContact;
		this.workUnit = workUnit;
		this.gender = gender;
		this.birthday = birthday;
		this.nativePlace = nativePlace;
		this.neighborhoodCommittee = neighborhoodCommittee;
		this.height = height;
		this.step = step;
		this.rh = rh;
		this.maritalStatus = maritalStatus;
		this.address = address;
		this.emergencyPerson = emergencyPerson;
		this.occupation = occupation;
		this.userId = userId;
		this.createTime = createTime;
		this.updateTime = updateTime;
		this.createUser = createUser;
		this.updateUser = updateUser;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false, length = 45)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@Column(name = "headPortrait", length = 200)
	public String getHeadPortrait() {
		return this.headPortrait;
	}

	public void setHeadPortrait(String headPortrait) {
		this.headPortrait = headPortrait;
	}

	@Column(name = "nationality", length = 45)
	public String getNationality() {
		return this.nationality;
	}

	public void setNationality(String nationality) {
		this.nationality = nationality;
	}

	@Column(name = "village", length = 45)
	public String getVillage() {
		return this.village;
	}

	public void setVillage(String village) {
		this.village = village;
	}

	@Column(name = "nation", length = 45)
	public String getNation() {
		return this.nation;
	}

	public void setNation(String nation) {
		this.nation = nation;
	}

	@Column(name = "weight", length = 45)
	public String getWeight() {
		return this.weight;
	}

	public void setWeight(String weight) {
		this.weight = weight;
	}

	@Column(name = "bloodType", length = 45)
	public String getBloodType() {
		return this.bloodType;
	}

	public void setBloodType(String bloodType) {
		this.bloodType = bloodType;
	}

	@Column(name = "education", length = 45)
	public String getEducation() {
		return this.education;
	}

	public void setEducation(String education) {
		this.education = education;
	}

	@Column(name = "residentType", length = 45)
	public String getResidentType() {
		return this.residentType;
	}

	public void setResidentType(String residentType) {
		this.residentType = residentType;
	}

	@Column(name = "emergencyContact", length = 45)
	public String getEmergencyContact() {
		return this.emergencyContact;
	}

	public void setEmergencyContact(String emergencyContact) {
		this.emergencyContact = emergencyContact;
	}

	@Column(name = "workUnit", length = 45)
	public String getWorkUnit() {
		return this.workUnit;
	}

	public void setWorkUnit(String workUnit) {
		this.workUnit = workUnit;
	}

	@Column(name = "gender", length = 45)
	public String getGender() {
		return this.gender;
	}

	public void setGender(String gender) {
		this.gender = gender;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "birthday", length = 19)
	public Date getBirthday() {
		return this.birthday;
	}

	public void setBirthday(Date birthday) {
		this.birthday = birthday;
	}

	@Column(name = "nativePlace", length = 45)
	public String getNativePlace() {
		return this.nativePlace;
	}

	public void setNativePlace(String nativePlace) {
		this.nativePlace = nativePlace;
	}

	@Column(name = "neighborhoodCommittee", length = 45)
	public String getNeighborhoodCommittee() {
		return this.neighborhoodCommittee;
	}

	public void setNeighborhoodCommittee(String neighborhoodCommittee) {
		this.neighborhoodCommittee = neighborhoodCommittee;
	}

	@Column(name = "height", length = 45)
	public String getHeight() {
		return this.height;
	}

	public void setHeight(String height) {
		this.height = height;
	}

	@Column(name = "step", length = 45)
	public String getStep() {
		return this.step;
	}

	public void setStep(String step) {
		this.step = step;
	}

	@Column(name = "rh", length = 45)
	public String getRh() {
		return this.rh;
	}

	public void setRh(String rh) {
		this.rh = rh;
	}

	@Column(name = "maritalStatus", length = 45)
	public String getMaritalStatus() {
		return this.maritalStatus;
	}

	public void setMaritalStatus(String maritalStatus) {
		this.maritalStatus = maritalStatus;
	}

	@Column(name = "address", length = 45)
	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	@Column(name = "emergencyPerson", length = 45)
	public String getEmergencyPerson() {
		return this.emergencyPerson;
	}

	public void setEmergencyPerson(String emergencyPerson) {
		this.emergencyPerson = emergencyPerson;
	}

	@Column(name = "occupation", length = 45)
	public String getOccupation() {
		return this.occupation;
	}

	public void setOccupation(String occupation) {
		this.occupation = occupation;
	}

	@Column(name = "userId", length = 45)
	public String getUserId() {
		return this.userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "createTime", length = 19)
	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updateTime", length = 19)
	public Date getUpdateTime() {
		return this.updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	@Column(name = "createUser", length = 45)
	public String getCreateUser() {
		return this.createUser;
	}

	public void setCreateUser(String createUser) {
		this.createUser = createUser;
	}

	@Column(name = "updateUser", length = 45)
	public String getUpdateUser() {
		return this.updateUser;
	}

	public void setUpdateUser(String updateUser) {
		this.updateUser = updateUser;
	}

	@Override
	public String toString() {
		return "ThUserInfo [id=" + id + ", headPortrait=" + headPortrait + ", nationality=" + nationality + ", village="
				+ village + ", nation=" + nation + ", weight=" + weight + ", bloodType=" + bloodType + ", education="
				+ education + ", residentType=" + residentType + ", emergencyContact=" + emergencyContact
				+ ", workUnit=" + workUnit + ", gender=" + gender + ", birthday=" + birthday + ", nativePlace="
				+ nativePlace + ", neighborhoodCommittee=" + neighborhoodCommittee + ", height=" + height + ", step="
				+ step + ", rh=" + rh + ", maritalStatus=" + maritalStatus + ", address=" + address
				+ ", emergencyPerson=" + emergencyPerson + ", occupation=" + occupation + ", userId=" + userId
				+ ", createTime=" + createTime + ", updateTime=" + updateTime + ", createUser=" + createUser
				+ ", updateUser=" + updateUser + "]";
	}

}
