package com.health.model;
// Generated 2017-1-20 10:46:12 by Hibernate Tools 5.0.2.Final


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ThUserFollow generated by hbm2java
 */
@Entity
@Table(name="th_user_follow"
    ,catalog="health"
)
public class ThUserFollow  implements java.io.Serializable {


     private Integer followId;
     private String userId;
     private String followUserId;
     private Integer quotaId;
     private String userRemark;
     private String followerRemark;
     private Date createTime;
 	 private String createUser;
 	 private Date updateTime;
 	 private String updateUser;
 	 private Integer flag;
 	 private Integer isMutualFollowed;

    public ThUserFollow() {
    }

    public ThUserFollow(String userId, String followUserId, Integer quotaId, String userRemark, String followerRemark, Date createTime, String createUser,
			Date updateTime, String updateUser, Integer flag, Integer isMutualFollowed) {
       this.userId = userId;
       this.followUserId = followUserId;
       this.quotaId = quotaId;
       this.userRemark = userRemark;
       this.followerRemark = followerRemark;
       this.createTime = createTime;
	   this.createUser = createUser;
	   this.updateTime = updateTime;
	   this.updateUser = updateUser;
	   this.flag = flag;
	   this.isMutualFollowed = isMutualFollowed;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="followId", unique=true, nullable=false)
    public Integer getFollowId() {
        return this.followId;
    }
    
    public void setFollowId(Integer followId) {
        this.followId = followId;
    }

    
    @Column(name="userId", length=50)
    public String getUserId() {
        return this.userId;
    }
    
    public void setUserId(String userId) {
        this.userId = userId;
    }

    
    @Column(name="followUserId", length=50)
    public String getFollowUserId() {
        return this.followUserId;
    }
    
    public void setFollowUserId(String followUserId) {
        this.followUserId = followUserId;
    }

    
    @Column(name="quotaId")
    public Integer getQuotaId() {
        return this.quotaId;
    }
    
    public void setQuotaId(Integer quotaId) {
        this.quotaId = quotaId;
    }

    
    @Column(name="userRemark", length=45)
    public String getUserRemark() {
        return this.userRemark;
    }
    
    public void setUserRemark(String userRemark) {
        this.userRemark = userRemark;
    }

    
    @Column(name="followerRemark", length=45)
    public String getFollowerRemark() {
        return this.followerRemark;
    }
    
    public void setFollowerRemark(String followerRemark) {
        this.followerRemark = followerRemark;
    }

    @Temporal(TemporalType.TIMESTAMP)
	@Column(name = "createTime", length = 19)
	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	@Column(name = "createUser", length = 45)
	public String getCreateUser() {
		return this.createUser;
	}

	public void setCreateUser(String createUser) {
		this.createUser = createUser;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updateTime", length = 19)
	public Date getUpdateTime() {
		return this.updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	@Column(name = "updateUser", length = 45)
	public String getUpdateUser() {
		return this.updateUser;
	}

	public void setUpdateUser(String updateUser) {
		this.updateUser = updateUser;
	}
	
	@Column(name = "flag")
	public Integer getFlag() {
		return this.flag;
	}

	public void setFlag(Integer flag) {
		this.flag = flag;
	}
	
	@Column(name = "isMutualFollowed")
	public Integer getIsMutualFollowed() {
		return this.isMutualFollowed;
	}

	public void setIsMutualFollowed(Integer isMutualFollowed) {
		this.isMutualFollowed = isMutualFollowed;
	}


}


